# Kanagawa Dragon dark palette shared by shell-driven tools.
typeset -g DOT_THEME_BG='#181616'
typeset -g DOT_THEME_FG='#c5c9c5'
typeset -g DOT_THEME_MUTED='#a6a69c'
typeset -g DOT_THEME_DIM='#0d0c0c'
typeset -g DOT_THEME_BLUE='#8ba4b0'
typeset -g DOT_THEME_CYAN='#8ea4a2'
typeset -g DOT_THEME_GREEN='#8a9a7b'
typeset -g DOT_THEME_YELLOW='#c4b28a'
typeset -g DOT_THEME_ORANGE='#b6927b'
typeset -g DOT_THEME_RED='#c4746e'
typeset -g DOT_THEME_MAGENTA='#a292a3'
typeset -g DOT_THEME_VIOLET='#938aa9'
typeset -g DOT_THEME_WHITE='#c8c093'
