# statusbar
set -g status on
set -g status-position bottom
set -g status-justify left
set -gF status-style "fg=#{@theme_blue},bg=#{@theme_bg}"
set -g status-interval 5
set -g status-left "#[fg=#{@theme_blue},bold]#S #[fg=#{@theme_dim}]| "
set -g status-right "#[fg=#{@theme_white}]#{?client_prefix,#[fg=#{@theme_yellow}]prefix #[fg=#{@theme_dim}]| ,}%H:%M"
set -g status-right-length 50
set -g status-left-length 30

setw -gF window-status-current-style "fg=#{@theme_blue},bg=#{@theme_dim},bold"
setw -g window-status-current-format ' #I:#W#F '

setw -gF window-status-style "fg=#{@theme_white},bg=#{@theme_bg},dim"
setw -g window-status-format " #[fg=#{@theme_white}]#I:#W#F "

# panes, copy mode, and messages
set -gF pane-border-style "fg=#{@theme_dim}"
set -gF pane-active-border-style "fg=#{@theme_blue}"
set -gF mode-style "fg=#{@theme_blue},bg=#{@theme_dim}"
set -gF message-style "fg=#{@theme_blue},bg=#{@theme_dim},bold"
set -gF message-command-style "fg=#{@theme_blue},bg=#{@theme_dim},bold"
