# statusbar
set -g status on
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=#268bd3,bg=#002c38'
set -g status-interval 5
set -g status-left '#[fg=#268bd3,bold]#S #[fg=#063540]| '
set -g status-right '#[fg=#9eabac]#{?client_prefix,#[fg=#b28500]prefix #[fg=#063540]| ,}%H:%M'
set -g status-right-length 50
set -g status-left-length 30

setw -g window-status-current-style 'fg=#268bd3,bg=#063540,bold'
setw -g window-status-current-format ' #I:#W#F '

setw -g window-status-style 'fg=#9eabac,bg=#002c38,dim'
setw -g window-status-format ' #[fg=#9eabac]#I:#W#F '

# panes, copy mode, and messages
set -g pane-border-style 'fg=#063540'
set -g pane-active-border-style 'fg=#268bd3'
set -g mode-style 'fg=#268bd3,bg=#063540'
set -g message-style 'fg=#268bd3,bg=#063540,bold'
set -g message-command-style 'fg=#268bd3,bg=#063540,bold'
